### ISSUE TITLE
Highlighting extension not preserving whitespace in <pre> tag

### ISSUE THREAD

**Issue by khushmeeet** [yuin/goldmark-highlighting#20]
I am using gold mark highlighting extension in my go code like this.
```go
highlighting.NewHighlighting(
    highlighting.WithStyle("monokai"),
),
```
and i define code in markdown this way
~~~
```json
{
  "site_title":"test",
  "email":"hello@flux.com",
  "twitter_username":"@test",
  "github_username":"test",
  "minify_css": true,
  "minify_html": true,
  "list": [
    "1",
    "2",
    "3"
  ],
  "map": {
    "a": 1,
    "b": 2
  }
}
```
~~~

After the rendering my formatted code block does not take whitespace or newlines into account and displays HTML like this.
<img width="845" alt="Screenshot 2021-07-08 at 6 30 34 PM" src="https://user-images.githubusercontent.com/8711912/124925919-96e08480-e01a-11eb-987b-d96234d71803.png">

Not sure, if this is a bug or I am missing some config option!

My full gold mark instantiation looks like this.
```go
md := goldmark.New(
		goldmark.WithExtensions(meta.Meta,
			highlighting.NewHighlighting(
				highlighting.WithStyle("monokai"),
			),
			extension.Footnote,
			extension.GFM,
			emoji.Emoji,
			mathjax.MathJax,
		),
		goldmark.WithRendererOptions(
			html.WithHardWraps(),
		),
		goldmark.WithParserOptions(
			parser.WithBlockParsers(),
			parser.WithAttribute(),
		),
	)
```

**Comment by yuin** [comment]
This seems a problem related your own CSS.
