### ISSUE TITLE
Proposal - Improve attribute parsing

### ISSUE THREAD

**Issue by jmooring** [yuin/goldmark-highlighting#28]
Users are accustomed to quoting HTML attributes, regardless of type, because many have no concept of type. And the browser doesn't care. I understand this is markdown, not HTML, but there is a similar expectation from non-developer users.

With this module, quoting or not quoting an attribute makes a big difference.

Example|Notes
:--|:--
`{linenostart="1"}`|Panic (see #27)
`{linenos="false"}`|Effectively setting it to true
`{hl_lines="[2]"}`|Ignored

**Comment by yuin** [comment]
This is not only for this extension, but for the [goldmark core](https://github.com/yuin/goldmark/blob/master/parser/attribute.go).

Could you create a new discussion in yuin/goldmark?
