### ISSUE TITLE
Prepare for breaking changes introduced in alecthomas/chroma v0.10.0

### ISSUE THREAD

**Issue by jmooring** [yuin/goldmark-highlighting#29]
Use `span` for `.line`, put code inside `<code>`
https://github.com/alecthomas/chroma/commit/d6e61d3cbed4f2349d7720b29c14d44ea90ca10d

Put lines in a div & code lines in a span, Add WrapLongLines Option
https://github.com/alecthomas/chroma/commit/5ed5054d7369706ea7c48993a254a833e194d289

**Comment by yuin** [comment]
I've merged PR #26. These changes will be applied in next version.
