### ISSUE TITLE
Missing styles? 

### ISSUE THREAD

**Issue by nilsherzig** [yuin/goldmark-highlighting#37]
Sorry if i'm missing something here but some styles as defined in https://github.com/alecthomas/chroma/tree/master/styles work for me (emacs, xcode-dark, ...) and some dont (rose-pine, catppuccin-mocha, ...). 

Is there anything i can do about that?

**Comment by nilsherzig** [comment]
nvm i just noticed that the chroma package used by this project is v2.2.0 which "only" provides these themes: 

```

abap.go
algol.go
algol_nu.go
api.go
arduino.go
autumn.go
average.go
base16-snazzy.go
borland.go
bw.go
colorful.go
doom-one.go
doom-one2.go
dracula.go
emacs.go
friendly.go
fruity.go
github.go
gruvbox.go
hr_dark.go
hr_high_contrast.go
igor.go
lovelace.go
manni.go
monokai.go
monokailight.go
murphy.go
native.go
nord.go
onesenterprise.go
paraiso-dark.go
paraiso-light.go
pastie.go
perldoc.go
pygments.go
rainbow_dash.go
rrt.go
solarized-dark.go
solarized-dark256.go
solarized-light.go
swapoff.go
tango.go
trac.go
vim.go
vs.go
vulcan.go
witchhazel.go
xcode-dark.go
xcode.go
``` 

Can we bump the chroma version to include new themes?

**Comment by andreaswilli** [comment]
Looks like this is still valid. Would be great to be able to use the new themes.
